Document: opensrf
Title: Debian opensrf Manual
Author: <insert document author here>
Abstract: This manual describes what opensrf is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/opensrf/opensrf.sgml.gz

Format: postscript
Files: /usr/share/doc/opensrf/opensrf.ps.gz

Format: text
Files: /usr/share/doc/opensrf/opensrf.text.gz

Format: HTML
Index: /usr/share/doc/opensrf/html/index.html
Files: /usr/share/doc/opensrf/html/*.html
